# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 68ab9330caa13f6e2d0822c8d570b2c62b5cb4b390c9c0d5dd981a6d43f10d2e0f51a5822f22345de36e961005e093ab75034041fcef8b09d7b48ba329bcf1af

test:
  secret_key_base: 7757537569b6edab76c469c95a39e9bcbf3b7200600da066634df54eea8e2c74da47537b10a7aa0dfe78209d1c3366f5625303a20764b450ca9db12c78ab8c7f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
